"""first

Revision ID: 99a1f1c47f11
Revises: 
Create Date: 2022-08-14 18:49:52.300796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a1f1c47f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_origo', sa.Text(), nullable=True),
    sa.Column('url_shortened', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urlT')
    # ### end Alembic commands ###
